### ISSUE TITLE
Disclosure indicator on Retina display

### ISSUE THREAD

**Issue by schoren** [taitems/iOS-Inspired-jQuery-Mobile-Theme#13]
Hello. When using this styles in a Retina display device, here's how the disclosure indicator looks:

![IOS inspired on retina display](http://skitch.com/nerohc/gdky1/ios-simulator)

**Comment by schoren** [comment]
Ups, the image didn't show. Here's the URL:

http://skitch.com/nerohc/gdky1/ios-simulator

**Comment by taitems** [comment]
Yikes. Yeah I really need to get my hands on a 4 or 4S to test with.

**Comment by schoren** [comment]
You can use the iOS simulator. Anyway, do you have any idea where to start
to fix this? I'll be happy to do it and contribute the patch
On Oct 25, 2011 7:02 PM, "Tait Brown" <
reply@reply.github.com>
wrote:

**Comment by taitems** [comment]
Awesome, I got the simulator running last night at home and replicated the issue. I'll fix ALL graphics tonight in one big batch.

**Comment by taitems** [comment]
This fix was just committed. More to come in regards to retina devices, but at least this one is done for now.
