### ISSUE TITLE
Footer icon does not show - e.g. <li><a href="#" id="locate" id="tabB" 

### ISSUE THREAD

**Issue by ns-1m** [taitems/iOS-Inspired-jQuery-Mobile-Theme#18]
Footer icon does not show up, if this example below
###### 

```
    <div data-role="footer" data-position="fixed">
        <div data-role="navbar">
          <ul>
           <li><a href="#searchpage" id="tabA" data-icon="custom">Search</a></li>          


           <li><a href="#" id="locate" id="tabB" data-icon="custom" >Location</a></li> 



           <li><a href="#layerspage" id="tabB" data-icon="custom"  data-transition="flip">Layers</a></li>
             <li><a href="#database" id="tabC" data-icon="custom" class="ui-btn-active">Spatialite</a></li>             <li><a href="#aboutpage" id="tabC" data-icon="custom" data-transition="flip">About</a></li>          

        </ul>
    </div><!-- /navbar -->
</div><!-- /footer -->
```
###### 

How do we remedy this 2 ids? One for the event and the other for the icon.

I think it would be good to have a look at this jQuery moble example and see these series of errors and messed ups.

http://openlayers.org/dev/examples/mobile-jq.html#mappage

Another thing, how many icons can be included in tabSprite.png?

And how do you add it? I tried to place another one (i.e. TabD) but it did not work as well.

Any instruction how and what is the format so the icons can be seen and displayed.

Thanks.

**Comment by taitems** [comment]
The demo theme is fairly hard coded when it comes to those bottom tabs as the icons do not belong to me, so I don't want to make it too easy to implement unless you've purchased the Glyphish set.

I'm assuming an basic to intermediate knowledge of code here, but, IDs <b>must</b> be unique for them to work. You'll need to modify the styles and replace <code>#tabA</code> etc. with actual classes like <code>.radar</code>, <code>.search</code> or <code>.locate</code> etc.

The <code>tabSprite.png</code> was produced in Photoshop from the Glyphish icon set. You'll need Photoshop to make more of these icons.
