### ISSUE TITLE
Non transparent overlay behind dialogs

### ISSUE THREAD

**Issue by iBobik** [taitems/iOS-Inspired-jQuery-Mobile-Theme#19]
Dialogs' overlays on the demo page are missing transparency. Overlay is transparent only during show and hide animation, else overlay is not transparent (have same color). 

Overlay show and hide animation shoul not be slide up and down but fade in and out. Only dialog should slide up and down.

I am using iPad 2 with iOS 5.

**Comment by taitems** [comment]
I'll have a look at this soon, but as far as I can tell - the transparent overlay is not possible. When this was first developed, jQuery mobile was treating the dialog as a "page" and not an overlay. Therefore if you made the background transparent, all the other pages were hidden so you could just see the body background, and that was it.

I'll have to see if that is still the case.

**Comment by taitems** [comment]
This prompted me to fire off a quick tweet:

http://twitter.com/#!/taitems/status/157254269173637120

And their two replies:

http://twitter.com/#!/jquerymobile/status/157267503247138816 http://twitter.com/#!/jquerymobile/status/157268041179217920

The situation is as I remembered, so we'll wait and see. A fix won't be immediate as the code base is ever changing.

**Comment by taitems** [comment]
Closing this. We've got the new popups with 1.2.0, lets see how they go.
