### ISSUE TITLE
StyleSheets need updates to work with JQM 1.1.0

### ISSUE THREAD

**Issue by hctv19** [taitems/iOS-Inspired-jQuery-Mobile-Theme#26]
With the release of the jQuery Mobile v 1.1.0 today, it appears that some of the styling overrides that previously worked in 1.0.1 are no longer working as intended. In playing around with things briefly I noticed that a second header section on an iPhone (such as a data selector) rendered with the background image being extremely thin and not taking up the whole header section. On an iPad, both the primary and secondary headers had major rendering issues involving the background image height. I'm sure there are a number of little tweaks that will be necessary to get everything to play well with the latest JQM version, so I just wanted to drop an issue in the queue as a heads up. Thanks for all your hard work on this project!

**Comment by taitems** [comment]
Thanks a bunch. I'll have a look when I get the chance. Getting it to work with 1.0.1 was pretty basic in the end, here's to hoping 1.1.0 is a similar level of effort.
