### ISSUE TITLE
Header buttons don't appear to be vertically centered

### ISSUE THREAD

**Issue by hctv19** [taitems/iOS-Inspired-jQuery-Mobile-Theme#28]
It doesn't look like the header buttons are quite vertically centered, it looks like there's slightly more space below the button than above (tested in iPad, Chrome, Firefox). Is this something that can fixed with a little style tweak?

Also - is there any chance you could add the PSDs to Git that you used to create that button backgrounds? It might make it easier to build customized themes this way.

Thanks for all of your hard work on this theme!

**Comment by taitems** [comment]
Should be fixed in the latest commit.

As for the PSD, it's just based off the Teehan+Lax files.
