### ISSUE TITLE
add style for button/list view links:  highlight on click

### ISSUE THREAD

**Issue by DivineDominion** [taitems/iOS-Inspired-jQuery-Mobile-Theme#30]
I created a quick fix to highlight listview links via CSS on tap/hold (more responsive!).  This is the code I added to a custom style sheet:

```
.ui-btn.ui-btn-down-c:not(.ui-slider-handle):not(label):not(.ui-btn-left):not(.ui-btn-right):not(.ui-input-clear) .ui-btn-text,
.ui-btn.ui-btn-down-c:not(.ui-slider-handle):not(label):not(.ui-btn-left):not(.ui-btn-right):not(.ui-input-clear) .ui-btn-text a,
.ui-page:not(.ui-dialog) .ui-content li.ui-btn.ui-btn-down-c p {
    color: white !important;
    text-shadow: none;
}
```

Also, it makes the text white & readable, which currently isn't the case (but it is like this on iOS).

**Comment by taitems** [comment]
Implemented in latest release. Good in desktop, a bit finicky in the mobile simulator.
