### ISSUE TITLE
Replace Current Toggle with iOS5 Slider

### ISSUE THREAD

**Issue by taitems** [taitems/iOS-Inspired-jQuery-Mobile-Theme#7]
The current toggle slider was never quite finished, and now that iOS5 is public we should replace the broken one with the official one.

**Comment by snez** [comment]
Will this be backwards compatible with iOS 4?

**Comment by taitems** [comment]
It's just a visual change, there's no compatibility to think of precisely.

Perhaps the iOS5 slider will be data-theme="a" or default, and then the old iOS4 one can be data-theme="b". The onus is then on the front end developer to sniff the User Agent string and potentially change the theme default.

The above solution would probably involve perfecting the look and feel of the iOS 4 slider which is something I'm shying away from. It's currently pretty ugly.
